# Generated by Django 3.1 on 2020-09-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200927_1232'),
        ('blog', '0002_auto_20200928_2229'),
    ]

    operations = [
    ]
