# Generated by Django 3.1 on 2020-09-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200905_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='Reply',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='Your_name',
        ),
    ]
