# Generated by Django 3.1 on 2020-09-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
