# Generated by Django 3.1 on 2020-09-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200906_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Crop Protection', 'Crop Protection'), ('Seeds', 'Seeds'), ('Irrigation', 'Irrigation'), ('Climate', 'Climate'), ('Soil/Land', 'Soil/Land'), ('Others', 'Others')], max_length=50),
        ),
    ]
