# Generated by Django 3.1 on 2020-09-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200906_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Crop Protection', 'Crop Protection'), ('Seeds', 'Seeds'), ('Irrigation', 'Irrigation'), ('Climate', 'Climate'), ('Soil/Land', 'Soil/Land'), ('Others', 'Others')], max_length=50),
        ),
    ]
