# Generated by Django 3.1 on 2020-09-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200918_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Select_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
